### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by dikonov**

### CODE REVIEW

**Comment by dikonov** [comment]
What does this mean:
continuous-integration/travis-ci/pr — The Travis CI build failed
???
The source .ts file may have a broken first <context> section. It has multiple closing tags (?) and no strings to translate. Should I copy this portion of strangely distorted xml from the source?

**Comment by dikonov** [comment]
OK. I got the access and uploaded the Russian strings to transifex. 

_They might still need some fixes because I could not insert the translation into the live modrana app and test it. It is necessary to check if all split pieces of sentences go well together syntactically and all menus fit the screen. The rpm does not have standard .qm files inside and I do not know where to put the compiled qm to make the app use it._ 

As for transifex, it's main drawback is high project entrance barrier. A volunteer translator has to wait for permissions to join and than to access his language indefinitely. The desire to do anything can vanish in the process.

**Comment by M4rtinK** [comment]
> OK. I got the access and uploaded the Russian strings to transifex.
Thanks!
> 
> They might still need some fixes because I could not insert the translation into the live modrana app and test it. It is necessary to check if all split pieces of sentences go well together syntactically and all menus fit the screen. The rpm does not have standard .qm files inside and I do not know where to put the compiled qm to make the app use it. Please, make a release with this translation and I shall update the strings if necessary.
Indeed, I really need to do a new release soon - the thing I'm working on right now (revamped navigation & improved voice instructions) is complex and will need still some more time, so it's bad to let users wait for other improvements such as translation updates.

And for the record, something is indeed wrong with how the translations are loaded on Sailfish OS - I had to do RPM package builds myself as well when testing the translation support code. I normally test during development by running modRana with qmlscene, but that would just not load the translation files.

> 
> As for transifex, it's main drawback is high project entrance barrier. A volunteer translator has to wait for permissions to join and than to access his language indefinitely. The desire to do anything can vanish in the process.

I agree this is sub-optimal and most importantly, what the hack is happening to the notifications about new join requests! I should be getting them (so I can approve them right away) but they seem to be getting lost in the void...

I'm actually fine with manually importing translations if they are sent in a reasonable format even though from the longer therm perspective there will be changes in the strings and that much easier to handle via Transifex both for me and for contributors. I've added an issue to document this: https://github.com/M4rtinK/modrana/issues/251

As for Transifex in general - the Fedora project uses Zanata for translations and that's still about 1000x times worse than Transifex. :)

**Comment by M4rtinK** [comment]
As the Russian translation has been uploaded to Transifex I'm closing this PR now - thanks a lot! :)

**Pull request closed without merging**
