### PR TITLE
add support for OSM Scout Server routing V2, fixes #207

### LINKED ISSUE #207: Add support for OSM Scout Server routing V2
With addition of Valhalla, OSM Scout Server supports new version of routing protocol - V2. This protocol follows Valhalla's API. Main changes when compared to V1:

* Routing points (target origin and points in between) have to be given as coordinates. So, client is supposed to apply geocoder itself before calling router. Use OSM Scout Server in this case to keep all operations offline.

* Routing response would be either Valhalla's response according to its API or libosmscout response in accordance with V1. Since V1 is implemented already, it should be easy to get that parsed.

* When user selected libosmscout as a routing provider in the server, the server will only use routing points to calculate the route and would determine the type of transpotration from provided JSON. All other Valhalla's API options are ignored.

* Valhalla's response encodes the route. See https://github.com/valhalla/valhalla-docs/blob/master/decoding.md for example code for decoding

There is an implementation in Poor Maps already. If licenses match, it should be easy to reuse that code.

### PR DESCRIPTION
**Pull request by rinigus**
This PR adds support for V2 routing protocol allowing to use it with Valhalla and libosmscout routing responses.

### CODE REVIEW

**Comment by M4rtinK** [comment]
Wow, thanks a lot! :)

I got back from Japan about 10 days ago (Japan was **really nice** - can only recommend!) but haven't really got to normal yet modRana development wise due to various things (unpacking, fighting jetlag, talking to friends about Japan, work, etc.) and I'll be on one more week of vacation next week - this time just in a cottage at the [Vranov dam lake](http://www.openstreetmap.org/search?query=vranov#map=13/48.9226/15.7658&layers=D) with friends. :)

After that I'll hopefully be able to get back to general modRana development & properly review & test (and likely outright merge) both of your pull requests. :)

BTW, thanks yet again for adding support for latin names in Japan/non latin countries - it worked just fine (once I actually managed to download the updated date over unstable hotel WiFi :) )!

I posted about it on Twitter - linking here in case you have not seen it yet:
https://twitter.com/M4rtinK/status/892228772597874689
https://twitter.com/M4rtinK/status/892228772597874689
There are also some pictures from our travels on my Twitter account in Japan in case you want to check them out. :)

**Comment by rinigus** [comment]
Its always good to take the break - and thank you for twitter messages (I am not using twitter though).

PS: Japan is impressive, indeed. I was there a while ago...

**Comment by rinigus** [comment]
Hi, any chance to look into this? :)

**Comment by M4rtinK** [comment]
> Hi, any chance to look into this? :)

Things have finally settled a bit so I'll take a look either today or during the weekend. :)

**Comment by M4rtinK** [comment]
This is what I was getting when testing the PR on Czech Republic data on my Jolla C:

`ERROR mod.routing.providers: OSM Scout Server routing: failed with exception
Traceback (most recent call last):
  File "./core/routing_providers.py", line 327, in search
    print(replyData)
UnicodeEncodeError: 'ascii' codec can't encode character '\u017e' in position 860: ordinal not in range(128)
`

Everything worked fine once I removed the print() calls.

**Comment by rinigus** [comment]
Yes, these print calls should be just dropped. Sorry for forgetting them in the code (used for debug)

**Comment by rinigus** [comment]
Print calls removed

**Comment by M4rtinK** [comment]
Thanks! Merging now! :)

**Pull request merged**
