### PR TITLE
Create harbour-modrana-sv_SE.ts

### PR DESCRIPTION
**Pull request by eson57**
Here's Swedish translation. I also requested language at Transifex.

### CODE REVIEW

**Comment by M4rtinK** [comment]
Thanks! :) And I've also accepted the language request on Transifex. :)

**Comment by eson57** [comment]
Great! Good for maintenance.  :)

**Comment by M4rtinK** [comment]
BTW, I've did some more translation fixes which added a few more strings & fixed the translation context for some of the existing ones.

**Comment by eson57** [comment]
No problem, I'll fix it as soon as you give me access to transifex.  ;)
Or I could do it here...?

**Comment by M4rtinK** [comment]
> No problem, I'll fix it as soon as you give me access to transifex translation. ;)
> Or I could do it here...?

I *think* I've already aproved the new language on Transifex - or do I still need to confirm something else (the UI for this part is not the best IMHO).

**Comment by eson57** [comment]
You are right, it's not the best approach. As it is, you'll have to confirm not only the new language but also every new translator. Translators can't even request translators access before language is confirmed. However, if you do know the translator, you can add him/her at the same time you confirm language. Just don't ask me how, because I don't know the project owners UI.

**Comment by M4rtinK** [comment]
> You are right, it's not the best approach. As it is, you'll have to confirm not only the new language but also every new translator. Translators can't even request translators access before language is confirmed. However, if you do know the translator, you can add him/her at the same time you confirm language. Just don't ask me how, because I don't know the project owners UI.

Yeah, that sucks - and more stuff:
- you have notifications that someone requested something, but you can't do the action from the notification itself
- the username matching seems broken - I wrote "eson" and it didn't find anything, but correctly added you once I wrote done
- it doesn't seem possible to add someone to a project from their profile page (so more manual clicking & copy pasting)

All in all while Transifex still has a better UI overall than what we use to localize Fedora (Zanata) it's surprising to see usability issues like this.

**Pull request merged**
